/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MqttConfigIndexRouteImport } from './routes/mqttConfig/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as BilibiliIndexRouteImport } from './routes/bilibili/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MqttConfigIndexRoute = MqttConfigIndexRouteImport.update({
  id: '/mqttConfig/',
  path: '/mqttConfig/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilibiliIndexRoute = BilibiliIndexRouteImport.update({
  id: '/bilibili/',
  path: '/bilibili/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bilibili/': typeof BilibiliIndexRoute
  '/home/': typeof HomeIndexRoute
  '/mqttConfig/': typeof MqttConfigIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bilibili': typeof BilibiliIndexRoute
  '/home': typeof HomeIndexRoute
  '/mqttConfig': typeof MqttConfigIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bilibili/': typeof BilibiliIndexRoute
  '/home/': typeof HomeIndexRoute
  '/mqttConfig/': typeof MqttConfigIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bilibili/' | '/home/' | '/mqttConfig/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bilibili' | '/home' | '/mqttConfig'
  id: '__root__' | '/' | '/bilibili/' | '/home/' | '/mqttConfig/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilibiliIndexRoute: typeof BilibiliIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  MqttConfigIndexRoute: typeof MqttConfigIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mqttConfig/': {
      id: '/mqttConfig/'
      path: '/mqttConfig'
      fullPath: '/mqttConfig/'
      preLoaderRoute: typeof MqttConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilibili/': {
      id: '/bilibili/'
      path: '/bilibili'
      fullPath: '/bilibili/'
      preLoaderRoute: typeof BilibiliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilibiliIndexRoute: BilibiliIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  MqttConfigIndexRoute: MqttConfigIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
